# Full-stack consumer: K3s + Cilium + cert-manager + ClusterIssuer +
# OAuth2-Proxy + soctalk-system, with cert-manager-minted TLS for both
# OAuth2-Proxy and SocTalk Ingresses.
#
# Production-shape end-to-end demonstration:
#   - cert-manager mints internal-CA-signed TLS certs.
#   - OAuth2-Proxy fronts the IdP at https://<host>/oauth2/*.
#   - soctalk-system reads X-Auth-Request-{User,Email} headers
#     forwarded by OAuth2-Proxy and is published at the
#     `mssp` / `customer` hostnames.
#
# Prerequisites (consumer-side):
#   1. CA materials staged at /var/lib/cert-manager/ca.{crt,key}.
#   2. OIDC client-id + client-secret staged at
#      /var/lib/oauth2-proxy/{client-id,client-secret}.
#      (cookie-secret is auto-generated by the loader on first boot.)
#   3. An ingress controller installed in the cluster matching
#      `ingress.className` (defaults to "traefik" everywhere; see
#      README.md for Traefik v3 / ingress-nginx install snippets).
#   4. DNS for `mssp.example.org` and `*.customers.example.org`
#      pointing at this host.
#
# Build:
#   nix build .#nixosConfigurations.edge-01.config.system.build.toplevel
#
# Deploy:
#   mkdir -p extra-files/var/lib/cert-manager extra-files/var/lib/oauth2-proxy
#   cp secrets/ca.crt           extra-files/var/lib/cert-manager/ca.crt
#   cp secrets/ca.key           extra-files/var/lib/cert-manager/ca.key
#   cp secrets/client-id        extra-files/var/lib/oauth2-proxy/client-id
#   cp secrets/client-secret    extra-files/var/lib/oauth2-proxy/client-secret
#   chmod 0400 extra-files/var/lib/cert-manager/ca.key \
#              extra-files/var/lib/oauth2-proxy/*
#   nix run github:nix-community/nixos-anywhere -- \
#     --extra-files ./extra-files --flake .#edge-01 root@<ip>
{
  description = "Full-stack soctalk-nixos consumer (cert-manager + OAuth2-Proxy + soctalk-system).";

  inputs = {
    soctalk-nixos.url = "path:../..";
    nixpkgs.follows = "soctalk-nixos/nixpkgs";
  };

  outputs = { self, nixpkgs, soctalk-nixos, ... }: {
    nixosConfigurations.edge-01 = soctalk-nixos.lib.mkHost {
      hostName = "edge-01";
      tenant = {
        timeZone = "Europe/Madrid";
        locale = "en_US.UTF-8";

        adminUsers = [
          { name = "ops"; description = "Operations admin"; }
        ];
        sshAuthorizedKeys = [
          # Placeholder — replace before deploying.
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExampleKeyDoNotUseInProduction ops@laptop"
        ];

        network = {
          interface = "ens18";
          address = "192.168.10.50";
          prefixLength = 24;
          gateway = "192.168.10.1";
          nameservers = [ "1.1.1.1" "9.9.9.9" ];
          domain = "example.org";
          enableIPv6 = false;
        };

        # cert-manager + CA ClusterIssuer signs the OAuth2-Proxy and
        # soctalk-system TLS certs.
        certManager.clusterIssuer = {
          enable = true;
          name = "internal-ca";
          type = "ca";
          ca.secretName = "ca-key-pair";
        };
        certManager.caSecret.enable = true;

        # OAuth2-Proxy frontend. Public at edge-01.example.org/oauth2/*.
        oidc = {
          enable = true;
          issuerUrl = "https://idp.example.org/";
          # host derives to "edge-01.example.org" automatically.
          ingress.className = "traefik";
          tls = {
            enable = true;
            # issuerRef defaults to "internal-ca" from clusterIssuer.name.
          };
          # cookie-secret auto-generated on first boot.
        };

        # SocTalk system. Published at mssp.example.org +
        # *.customers.example.org, fronted by OAuth2-Proxy.
        system = {
          enable = true;

          # Required UUIDs and labels. Generate the UUIDs once and pin
          # them — the chart's installation identity is keyed off them.
          install = {
            # `uuidgen | tr A-Z a-z`
            msspId = "11111111-1111-1111-1111-111111111111";
            msspName = "Acme Security";
            installId = "22222222-2222-2222-2222-222222222222";
            installLabel = "pilot-prod";
          };

          ingress = {
            className = "traefik";
            hostnames = {
              mssp = "mssp.example.org";
              customer = "*.customers.example.org";
            };
          };

          tls = {
            enable = true;
            # issuerRef defaults to "internal-ca" from clusterIssuer.name.
            # includeWildcard = false → only mssp.example.org is in the
            # rendered Certificate's dnsNames. Wildcard customer host
            # needs a separately-managed cert (DNS-01 issuer required).
          };

          # oidc.trustedHeader* / trustedProxyCIDRs all defaulted to
          # match the OAuth2-Proxy + Cilium pod CIDR configuration above.

          postgres = {
            enable = true;
            storage.size = "20Gi";
          };
        };
      };
    };
  };
}
